name: flutter_counter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  responsive_framework: ^0.2.0
  http: ^0.13.6
  shared_preferences: ^2.1.1
  expandable: ^5.0.1
  flutter_map: ^4.0.0
  location: ^4.4.0
  latlong2: ^0.8.1
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/icons/puzzle.png"


